### ISSUE TITLE
"ValueError: Invalid webhook URL provided"

### ISSUE THREAD

**Issue by Sami6494** [kyb3r/dhooks#37]
Discord appears to  have changed webhooks and now whenever I try to use it I get a ValueError message, this only happens with the newly generated webhooks, all the old ones seem to work fine.

My Sample Code:
![Code](https://user-images.githubusercontent.com/68126994/88571618-8ef32480-d003-11ea-92e5-a1a1816f4cf2.png)

Error message:
![ErrorMessage](https://user-images.githubusercontent.com/68126994/88571625-91557e80-d003-11ea-81d6-346455208ee2.png)

**Comment by mischievousdev** [comment]
What is your dhooks version?

**Comment by Sami6494** [comment]
1.1.4

**Comment by mischievousdev** [comment]
Update dhooks, latest fix will resolve the issue

**Comment by Sami6494** [comment]
updated using pip and says that v1.1.4 is the latest

**Comment by mischievousdev** [comment]
Sorry my bad that's the latest version

**Comment by DAzVise** [comment]
I've just tried with 2 webhooks (old and new) and both worked as expected, what discord client are you using? for ex: regular discord or canary etc

**Comment by DAzVise** [comment]
actually, can you run this code and return the output? ```py
import re
hook_url = "webhook url"

def hook_test1():
    URL_REGEX = r'^(?:https?://)?((canary|ptb)\.)?discord\.com/api/webhooks/(?P<id>[0-9]+)/(?P<token>[A-Za-z0-9\.\-\_]+)/?$'
    print(bool(re.match(URL_REGEX, hook_url)))

def hook_test2():
    URL_REGEX = r'^(?:https?://)?((canary|ptb)\.)?discord(app)?\.com/api/webhooks/(?P<id>[0-9]+)/(?P<token>[A-Za-z0-9\.\-\_]+)/?$'
    print(bool(re.match(URL_REGEX, hook_url)))

hook_test1()
hook_test2()
```

**Comment by Sami6494** [comment]
Regular discord on my pc, I noticed that the new webhooks seem to have a different layout than the old ones

**Comment by Sami6494** [comment]
Still getting the same error:

`Traceback (most recent call last):
  File "c:/Users/samib/Documents/Python/Projects/newwebhooks.py", line 3, in <module>
    hook = Webhook('https://discordapp.com/api/webhooks/736933475734519898/R5_mA80O-Yrm0Xds_TBHjfpYrp5xIKc5M0369KoC3dNMqX-24OPkrKjltCqmiW6YuNIC')
  File "C:\Users\samib\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dhooks\client.py", line 144, in __init__
    self._parse_or_format_url()
  File "C:\Users\samib\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dhooks\client.py", line 482, in _parse_or_format_url
    raise ValueError('Invalid webhook URL provided.')
ValueError: Invalid webhook URL provided.
PS C:\Users\samib\Documents\Python> `

**Comment by DAzVise** [comment]
oh i see, that webhook is still using the discordapp domain (you forgot to blur it 😅), i'll PR a fix but in the meantime replace discordapp.com with discord.com from your url

**Comment by Sami6494** [comment]
Thanks, its alright this is on a test account and server

**Comment by DeJMan** [comment]
![I changed it to discord.com instead and it still didn't work](https://user-images.githubusercontent.com/8005072/88716398-11790280-d130-11ea-8e96-9d8350d819de.jpg)

**Comment by DAzVise** [comment]
are you using the latest version of dhooks (1.1.4)?

**Comment by DeJMan** [comment]
Ah I thought I was.

Apparently, heroku was using cached dependencies of an older dhooks library even though locally I was using the latest one.

Bit of tinkering and I got it to clear cache and update. It works fine now, thanks.

**Comment by S0V3T** [comment]
Have same issue

**Comment by DAzVise** [comment]
> Have same issue
Read through this and you'll hopefully find a fix for your issue, @kyb3r also needs to push the latest bug fix to pypi

**Comment by TaquitoSlayer** [comment]
mans still hasnt pushed it 

put the beer down with the boys and push it ya do it for the culture
