### ISSUE TITLE
bad request error

### ISSUE THREAD

**Issue by Dmunch04** [kyb3r/dhooks#42]
i keep getting this error when trying to send a webhook embed
```
Traceback (most recent call last):
  File "C:\Users\Daniel\Documents\python\hypemonitor\test.py", line 99, in <module>
    supreme_monitor.main_loop()
  File "C:\Users\Daniel\Documents\python\hypemonitor\test.py", line 86, in main_loop
    self.send_restock_discord_webhook(temp)
  File "C:\Users\Daniel\Documents\python\hypemonitor\test.py", line 60, in send_restock_discord_webhook
    webhook.send(embed=embed)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python38\lib\site-packages\dhooks\client.py", line 275, in send
    return self._request('POST', payload, file=file)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python38\lib\site-packages\dhooks\client.py", line 388, in _request
    resp.raise_for_status()
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://discord.com/api/webhooks/...
```

**Comment by Dmunch04** [comment]
okay nvm its because of the image im trying to give it. for some reason it wont work
