### ISSUE TITLE
base64 obfuscation preventing me from setting an image

### ISSUE THREAD

**Issue by gumbobrot** [kyb3r/dhooks#54]
```
C:\Users\Jonas\Documents\GitHub\Rose-Injector\components\source>main.py
Traceback (most recent call last):
  File "C:\Users\SECRET\Documents\GitHub\Rose-Injector\components\source\main.py", line 5, in <module>
    import rose_rat
  File "C:\Users\SECRET\Documents\GitHub\Rose-Injector\components\source\rose.py", line 187, in <module>
    cmdhandler = CommandHandler()
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\SECRET\Documents\GitHub\Rose-Injector\components\source\rose.py", line 26, in __init__
    self.webhook = _WebhookX().get_object()
                   ^^^^^^^^^^^
  File "C:\Users\SECRET\Documents\GitHub\Rose-Injector\components\source\__webhook.py", line 10, in __init__
    self.webx.modify(name=cc.get_name(), avatar=requests.get(cc.get_avatar()).content)
  File "C:\Users\SECRET\AppData\Local\Programs\Python\Python311\Lib\site-packages\dhooks\client.py", line 297, in modify
    payload['avatar'] = bytes_to_base64_data(avatar)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SECRET\AppData\Local\Programs\Python\Python311\Lib\site-packages\dhooks\utils.py", line 53, in bytes_to_base64_data
    mime = mime_type(data)
           ^^^^^^^^^^^^^^^
  File "C:\Users\SECRET\AppData\Local\Programs\Python\Python311\Lib\site-packages\dhooks\utils.py", line 48, in mime_type
    raise ValueError('Unsupported image type given.')
ValueError: Unsupported image type given.
```

That's the error I get.
My code is the following:
```py
from dhooks import Embed, File, Webhook 
from config import Config 
import requests
import os
cc = Config()

class _WebhookX():
    def __init__(self):
        self.webx = Webhook(cc.get_webhook())
        self.webx.modify(name=cc.get_name(), avatar=requests.get(cc.get_avatar()).content)

    def get_object(self):
        return self.webx
```

And the config file looks like this:
```py
        self.secr_eb_color = 'MTY3MTE2ODA='
        self.secr_eb_footer = 'Um9zZS1JbmplY3RvciB8IE1hZGUgYnkgR3VtYm9icm90LCBJQ0V4RlMsIHN1ZWdkdSBhbmQgeHBpZXJyb3ogfCBodHRwczovL2dpdGh1Yi5jb20vRGFtYWdpbmdSb3NlL1Jvc2UtSW5qZWN0b3I='
        self.secr_wh_avatar = 'aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0RhbWFnaW5nUm9zZS9Sb3NlLUluamVjdG9yL21haW4vcmVhZG1lL1Jvc2UuanBlZw=='
        self.secr_wh_name = 'Um9zZS1JbmplY3Rvcg=='
        self.eb_color = int(base64.b64decode(self.secr_eb_color.encode('ascii')).decode('ascii'))
        self.eb_footer = str(base64.b64decode(self.secr_eb_footer.encode('ascii')).decode('ascii'))
        self.wh_avatar = str(base64.b64decode(self.secr_wh_avatar.encode('ascii')).decode('ascii'))
        self.wh_name = str(base64.b64decode(self.secr_wh_name.encode('ascii')).decode('ascii'))
```

I poorly encoded it with base64 because some dude threatened me that he would skid all our tools and build malware into them. He has absolutely no knowledge of Python, so I tried to include base64 in it.

**The reason because I'm creating this issue is, I cannot find anyone else having this problem.**

**Comment by gumbobrot** [comment]
nvm i fixed it

**Comment by TheLovinator1** [comment]
How did you fix it?

**Comment by gumbobrot** [comment]
by using build in hex adecimals, and if i wanted to use it with b64 then i'd need to decode them directly where they are used i think

**Comment by gumbobrot** [comment]
btw, is the discordapp -> discord thing already fixed? i think it wasn't like that in older versions

**Comment by TheLovinator1** [comment]
> btw, is the discordapp -> discord thing already fixed? i think it wasn't like that in older versions

It is fixed in the repo but he version on PyPI is old, you should just use https://github.com/lovvskillz/python-discord-webhook instead

**Comment by gumbobrot** [comment]
> > btw, is the discordapp -> discord thing already fixed? i think it wasn't like that in older versions
> 
> It is fixed in the repo but he version on PyPI is old, you should just use https://github.com/lovvskillz/python-discord-webhook instead

hmm, i've never had this issue before when i was using older versions

for my project, it would be to much work to implement or rewrite everything to the lib you provided, its easier for me just detect the discordapp.com and then replace it with discord.com over the re module
